version: "3.8"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  faq_api:
    build: .
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - ollama
      - mongo
    ports:
      - "8000:8000"