apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-faq-api
  namespace: staging
  labels:
    app: llm-faq-api
    environment: staging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: llm-faq-api
  template:
    metadata:
      labels:
        app: llm-faq-api
        environment: staging
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: llm-faq-api
        image: {{ECR_REGISTRY}}/llm-faq-api:{{IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: llm-faq-api-config
        - secretRef:
            name: llm-faq-api-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
        - name: ollama-data
          mountPath: /home/appuser/.ollama
      volumes:
      - name: ollama-data
        emptyDir:
          sizeLimit: 3Gi
